### PR TITLE
Upgraded scala and sbt version to 2.12.3 and 1.0.1 respectively.

### PR DESCRIPTION
**Pull request by vi-kas**
Upgraded sbt and scala versions.

### CODE REVIEW

**Comment by sksamuel** [comment]
:+1:

**Comment by sksamuel** [comment]
I'll do a release now.

**Comment by sksamuel** [comment]
This PR seems to have broken publishing.

[info] Starting release process off commit: b277e12c68574a8ba2e32d1c21927c788eadd6f8
[error] java.lang.RuntimeException: Repository for publishing is not specified.
[error] 	at scala.sys.package$.error(package.scala:27)
[error] 	at sbt.Classpaths$.$anonfun$getPublishTo$1(Defaults.scala:2389)

**Comment by vi-kas** [comment]
Check this new PR:
https://github.com/sksamuel/sbt-scapegoat/pull/52

**Pull request merged**
