### PR TITLE
Fix minimal warn level

### PR DESCRIPTION
**Pull request by ches**
The SettingKey is being interpolated rather than its value, i.e.

```
[info] * -P:scapegoat:minimalWarnLevel:SettingKey(This / This / This / scapegoatMinimalWarnLevel)
```

### CODE REVIEW

**Comment by ches** [comment]
@sksamuel @mccartney

**Comment by ches** [comment]
Could we have a release with this fix please? It's been a year now 😅

**Comment by mccartney** [comment]
> Could we have a release with this fix please?

@sksamuel 
(I don't think I have permissions to perform a release in this repo)

**Comment by sksamuel** [comment]
1.1.1 has been released.

**Pull request merged**
