### PR TITLE
Scapegoat library dep should be of the correct Scala version

### LINKED ISSUE #55: Cross version blocker
While trying to upgrade to SBT 1.0.3, is seems that the dependency to scala-xml added by sbt-scapegoat is breaking the cross compilation:

```
[error]    org.scala-lang.modules:scala-xml _2.12, _2.11
[error] java.lang.RuntimeException: Conflicting cross-version suffixes in: org.scala-lang.modules:scala-xml
[error] 	at scala.sys.package$.error(package.scala:27)
[error] 	at sbt.librarymanagement.ConflictWarning$.processCrossVersioned(ConflictWarning.scala:39)
[error] 	at sbt.librarymanagement.ConflictWarning$.apply(ConflictWarning.scala:19)
[error] 	at sbt.Classpaths$.$anonfun$ivyBaseSettings$64(Defaults.scala:1971)
[error] 	at sbt.Classpaths$$$Lambda$1109/1112560756.apply(Unknown Source)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:44)
[error] 	at scala.Function1$$Lambda$997/1585776625.apply(Unknown Source)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:42)
[error] 	at sbt.internal.util.$tilde$greater$$Lambda$1828/1422262786.apply(Unknown Source)
[error] 	at sbt.std.Transform$$anon$4.work(System.scala:64)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:257)
[error] 	at sbt.Execute$$Lambda$1845/2116248721.apply(Unknown Source)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error] 	at sbt.Execute.work(Execute.scala:266)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:257)
[error] 	at sbt.Execute$$Lambda$1836/127758389.apply(Unknown Source)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:167)
[error] 	at sbt.ConcurrentRestrictions$$anon$4$$Lambda$1843/1340928776.apply(Unknown Source)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:32)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[error] 	at java.lang.Thread.run(Thread.java:745)
```

```
sbt> dependencyTree

[info] Done updating.
[info] ...
[info]   +-com.sksamuel.scapegoat:scalac-scapegoat-plugin_2.12:1.3.3 [S]
[info]     +-org.scala-lang.modules:scala-xml_2.12:1.0.5 [S]
[info]     +-org.scala-lang:scala-reflect:2.11.11 [S]
```

### PR DESCRIPTION
**Pull request by pomadchin**
Fixes #55

@cchantep does that work for you?

### CODE REVIEW

**Comment by cchantep** [comment]
Seems so, I would also update it to the `Provided` scope, as required to build but not at runtime (I'm used to exclude it using assembly)

**Comment by pomadchin** [comment]
@cchantep done, added as a separate commit. Want to hear @sksamuel opinion about these changes.

**Comment by sksamuel** [comment]
:+1:

**Comment by pomadchin** [comment]
yo @sksamuel, are there any release dates with this fix? ^^'

**Pull request merged**
