### PR TITLE
Add a separate task to run the scapegoat checks.

### LINKED ISSUE #19: Create sbt task for scapegoat
Currently configuring an sbt project to use scapegoat has the effect that scapegoat will run during the compile phase, as configured, every time.

Please create an sbt task that will allow scapegoat to run on demand, and decouple from running during the default compilation phase, as is the case with [scalastyle](http://www.scalastyle.org/sbt.html#usage). This will allow users to optionally run scapegoat periodically, and otherwise run the build without penalizing compile times.

### PR DESCRIPTION
**Pull request by gregsymons**
Fixes #19.

### CODE REVIEW

**Comment by sksamuel** [comment]
Does it still work without invoking scapegoat. I see you've added the extra scapegoat config.

**Comment by gregsymons** [comment]
This changes the current default behavior in that the checks will not run automatically during compile any more, but it should work fine with sbt 0.13.5, probably earlier versions as well.

**Comment by sksamuel** [comment]
I'm ok with that, but I should bump the versions properly to reflect its a breaking change.

**Comment by sksamuel** [comment]
Also I assume the new behaviour is sbt scapegoat:compile ?

**Comment by gregsymons** [comment]
Sort of... it's easier to just do `scapegoat`, which will do a clean first to make sure everything gets checked.

**Comment by gregsymons** [comment]
Are there any issues with this change that are still holding it up?

**Comment by sksamuel** [comment]
No, I can put out a release tonight.

**Comment by gregsymons** [comment]
I assume the compiler plugin's already been released? Or will you do that tonight, too?

**Comment by sksamuel** [comment]
Yep do both same time.

**Comment by gregsymons** [comment]
Sweet! Thanks.

**Comment by sksamuel** [comment]
Released, please allow 15 minutes or so for it to work. 0.94.7 is the
version string.

**Comment by gregsymons** [comment]
Um, hate to be a bother, but you forgot to pull in the pull request :) I'll rebase on top of the new release so that it'll merge properly.

**Comment by sksamuel** [comment]
Which commit? I git a fresh clone of both repos before pushing.

**Comment by gregsymons** [comment]
The original commit was @61dbb0a, but I rebased it after the release, so now it's @8e6ff32.

**Comment by sksamuel** [comment]
I was confused but now I understand. I never actually merged the PR.

**Comment by sksamuel** [comment]
Can you do one to update the docs please.

**Comment by sksamuel** [comment]
1.0.0 is released now.

**Pull request merged**
